name: "quay-vulnerability-check"
description: "GitHub Action for reporting Docker image vulnerabilities on Quay registry"

inputs:
  organization:
    description: "The organization name on Quay.io where the repository is located."
    required: true
  repository:
    description: "The name of the repository on Quay.io to check for vulnerabilities."
    required: true
  image_tag:
    description: "The tag of the Docker image in the specified repository to check for vulnerabilities."
    required: true
  quay_token:
    description: "The Quay.io authentication token with necessary permissions to access the repository and perform vulnerability checks."
    required: true
  severities:
    description: "Comma-separated list of allowed severities. Example: 'High,Critical'. If not provided, all severities will be considered. Allowed values: Unknown, Low, Medium, High, Critical."
    required: false
  exit_code:
    description: "The exit code to be set if vulnerabilities are found. Allowed values: 0 (default) or 1."
    required: false
    default: "0"

runs:
  using: "docker"
  image: "docker://ghcr.io/atilsensalduz/quay-image-vulnerability-check-action:v0.5.0"
