name: "quay-vulnerability-check"
description: "GitHub Action for reporting Docker image vulnerabilities on Quay registry"

inputs:
  organization:
    description: "The organization name on Quay.io where the repository is located."
    required: true
  repository:
    description: "The name of the repository on Quay.io to check for vulnerabilities."
    required: true
  image_tag:
    description: "The tag of the Docker image in the specified repository to check for vulnerabilities."
    required: true
  quay_token:
    description: "The Quay.io authentication token with necessary permissions to access the repository and perform vulnerability checks."
    required: true

runs:
  using: "docker"
  image: "docker://ghcr.io/atilsensalduz/quay-image-vulnerability-check-action:0.0.1"
