name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build and Publish the Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: "Login to GitHub Container Registry"
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}

        - name: Get Latest Tag
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          id: get-latest-tag
          
        - name: Build, tag, and push image to GHCR
          id: build-image
          run: |
            # Build a docker container and push it to GHCR
            docker build -t ghcr.io/atilsensalduz/quay-image-vulnerability-check-action:$$RELEASE_VERSION .
            echo "Pushing image to GHCR..."
            docker push ghcr.io/atilsensalduz/quay-image-vulnerability-check-action:$$RELEASE_VERSION
