name: Build

on:
    release:
        types: [published]
    
jobs:
  build:
    name: Build and Publish the Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: "Login to GitHub Container Registry"
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}
          
        - name: Build, tag, and push image to GHCR
          id: build-image
          run: |
            # Build a docker container and push it to GHCR
            TAG="${{ github.ref_name }}"
            docker build -t ghcr.io/atilsensalduz/quay-image-vulnerability-check-action:v${TAG:1} .
            echo "Pushing image to GHCR..."
            docker push ghcr.io/atilsensalduz/quay-image-vulnerability-check-action:v${TAG:1}
