name: Integration Test
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update action.yml to build locally
        run: |
          sed -i 's/.*image\:.*/  image\: \"Dockerfile\"/' action.yml
          cat action.yml
      - name: Self test
        id: selftest
        uses: ./
        with:
            organization: ${{ secrets.QUAY_ORGANIZATION }}
            repository: ${{ secrets.QUAY_REPOSITORY }}
            image_tag: ${{ secrets.IMAGE_TAG }}
            quay_token: ${{ secrets.QUAY_TOKEN }}
      - name: Check Report
        run: |
          cat vulnerabilities_report.md >> $GITHUB_STEP_SUMMARY
